#! /usr/bin/env ruby

conf="/etc/mimicus/mimicus.conf"

begin

require 'vmstat'
require 'yaml'
require 'socket'

config = YAML.load_file(conf)

port = config['port']

#port = 2000


server = TCPServer.new port # Server bound to port 2000
hostname = Socket.gethostname

puts "Mimicus agent is running on TCP port: #{port}"
puts "Press Control-C to exit"

loop do
  client = server.accept    # Wait for a client to connect
  client.puts hostname 
  client.puts Vmstat.boot_time 
  client.puts Vmstat.cpu 
  client.puts Vmstat.memory 
  client.puts Vmstat.memory 
  client.puts "Time is #{Time.now}"
  client.close
end

puts "test"
rescue Interrupt
  puts "\nexiting..."
rescue Exception => e
puts e
end
